### ISSUE TITLE
TODO: Fix .gitignore file and create basic movement system.

### ISSUE THREAD

**Issue by xsolvia** [electricdanwa/theHub#2]
- [ ] .gitignore file is setup
 - [ ] movement is made (with rigidbodys)
 - [ ] make movement work on multiplayer
